version: '3'

services:
  minecraft:
    build:
      context: .
      args:
        MINECRAFT_VERSION: "1.21.11"
    ports:
      - "54321:25565"
    environment:
      - MINECRAFT_VERSION=1.21.11
    volumes:
      - ./data:/data
